version: '2'
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
        volumes:
            - ./esdata:/usr/share/elasticsearch/data
        environment:
          - discovery.type=single-node
    kibana:
        image: docker.elastic.co/kibana/kibana:7.6.0
        ports:
            - "127.0.0.1:5601:5601"
        links:
            - elasticsearch
    screeps-stats:
        build: .
        links:
            - elasticsearch:elasticsearch
        entrypoint: wait-for-it/wait-for-it.sh -t 30 elasticsearch:9200 -- python screeps_etl/screepsstats.py
