version: '3.5'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:7.6.0
    ports:
      - "127.0.0.1:5601:5601"
  screeps-stats:
    depends_on:
      - elasticsearch
    build: .
    entrypoint: wait-for-it/wait-for-it.sh -t 30 elasticsearch:9200 -- python screeps_etl/screepsstats.py
networks:
  webnet:
    driver: overlay
    attachable: true # Needed in order to run custom commands in the container
